### ISSUE TITLE
Balance Bot example broken due to cdn certificate issue

### ISSUE THREAD

**Issue by Nashenas88** [copper-project/copper-rs#113]
This is not an issue with the code itself, but with the configuration of the cdn for delivering the glb. Could the project be updated to store the assets in the repo instead?

```
Failed to download and cache balancebot.glb: HttpError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("cdn.copper-robotics.com")), port: None, path: "/balancebot.glb", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "tls_post_process_server_certificate", reason: "certificate verify failed", file: "../ssl/statem/statem_clnt.c", line: 1883 }]))) }, X509VerifyResult { code: 62, error: "hostname mismatch" })) })
```

Going to https://cdn.copper-robotics.com/ results in
![screenshot-2024-11-25-19-26-00](https://github.com/user-attachments/assets/43d466c5-394c-49ab-b66c-b68d7e3c3695)

**Comment by gbin** [comment]
Oh noo! You know what? A CDN works better when you pay your bill :).

It should be back now, tell me if you still have the issue.

Sorry about that.
Thanks for trying Copper and enjoy the demo :)

BTW: initially I put those on github LFS but they are really not reasonable with their pricing.
