### ISSUE TITLE
Example of reading log from index and log in rust

### ISSUE THREAD

**Issue by lingfei1999** [copper-project/copper-rs#20]
Hi, thanks for open-sourcing the lib. I'm interested in using the log without copper, do you have any simple example of reading the log and/or streaming log to a file that can be rotated to a centralized log server later?
Thanks

**Comment by lingfei1999** [comment]
Thanks for the fast response. yeah, I saw the python, can we have an example that reads the log in rust as well?

**Comment by gbin** [comment]
Oh you just need to feed the file + index  to this function in Rust: https://github.com/copper-project/copper-rs/blob/master/cu29_export/src/lib.rs#L125

**Comment by gbin** [comment]
@lingfei1999 hopefully you are good to go on this one otherwise feel free to reopen the issue! Thanks
